### PR TITLE
Fix sporadic crashes caused by finding classes that don't play well with isSubclass(of:)

### LINKED ISSUE #1155: Risky subclass checking in QuickSpec and QuickConfiguration
### What did you do?

When running tests, I run into sporadic crashes in `QuickConfiguration.configureSubclassesIfNeededWithWorld`. 

Similar to these issues
https://github.com/Quick/Quick/issues/1114
https://github.com/Quick/Quick/issues/1025

### What did you expect to happen?

I expect there to be no crash.

### What actually happened instead?

It crashes.

### Environment

List the software versions you're using:

 - Quick: *4.0.0*
 - Nimble: *9.2.1*
 - Xcode Version: *13.3.1*
 - Swift Version: *5.6*

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - CocoaPods: *1.11.3*

### PR DESCRIPTION
**Pull request by younata**
Also grabs the list of objc classes in a much more thread-safe way.

Fixes #1155

---

This changes how we determine if a given class is a subclass of QuickSpec or QuickConfiguration. This is likely slower than using `isSubclass(of:)`. However, according to the radar @tiarnann filed, this should eliminate the sporadic crashes in subclass detection that keep coming up. So that's definitely worth fixing the issue.

Additionally, this replaces usage of `objc_getClassList` with `objc_copyClassList`. Apparently the get method has potential race conditions that can cause crashes, while the copy method does not.

### CODE REVIEW

File: Sources/Quick/QuickTestObservation.swift [hunk 1]
```diff
@@ -45,24 +45,18 @@ extension QuickSpec {
         if let subclasses = subclasses {
             subjects = subclasses
         } else {
-            let classesCount = objc_getClassList(nil, 0)
+            // See https://developer.apple.com/forums/thread/700770.
+            var classesCount: UInt32 = 0
+            guard let classList = objc_copyClassList(&classesCount) else { return }
+            defer { free(UnsafeMutableRawPointer(classList)) }
+            let classes = UnsafeBufferPointer(start: classList, count: Int(classesCount))
```
Comment (jessesquires) [inline Sources/Quick/QuickTestObservation.swift:52]: Could we extract this into a helper function and reuse it?

**Review by jessesquires — APPROVED** [review]
thanks @younata! 💯 looks good

**Comment by jessesquires** [comment]
@younata danger is failing because you are pulling from a fork. 

if you branch directly from the repo, danger should run successfully. but not a big deal.

File: Sources/Quick/QuickTestObservation.swift (hunk 1 above)
Comment (younata) [reply Sources/Quick/QuickTestObservation.swift]: Done.

**Comment by younata** [comment]
> @younata danger is failing because you are pulling from a fork.
> 
> if you branch directly from the repo, danger should run successfully. but not a big deal.

Oops. Future PRs from me will be from a branch on this repo.
