### PR TITLE
Initial support to implicit errors

### LINKED ISSUE #403: Catch thrown errors in tests
If you are writing a test in swift 2.0 and use `throws` the test should expect throwing functions and fail automatically if the function throws.

```
func aThrowingFunction() throws -> String {
  return "something"
}

class SomeTest: QuickSpec {
  override func spec() {
    describe("hanlding throwing functions") {
      it("should compile when having function that throws") {
        aThrowingFunction() // <- this should compile. test should fail if function throws
      }
    }
  }
}
```

### PR DESCRIPTION
**Pull request by marcelofabri**
This adds support to catching thrown errors inside `it` blocks. Will fix #403.

Currently, you'd have to use one of Nimble's matchers such as 

```swift
it("works") {
    expect { try foo }.toNot(throwError())
}
```

With this, you'd just have:
```swift
it("works") {
    try foo
}
```

This also is similar to `XCTest`, which supports functions being marked as `throws` (and the test fails if they do throw). 

This is still WIP because I don't know how to proceed on some places (will add comments).

Checklist - While not every PR needs it, new features should consider this list:

 - [ ] Does this have tests? Not yet
 - [ ] Does this have documentation? Not yet
 - [x] Does this break the public API (Requires major version bump)? No
 - [x] Is this a new feature (Requires minor version bump)? Yes

### CODE REVIEW

File: Sources/Quick/Example.swift [hunk 1]
```diff
@@ -71,7 +71,11 @@ final public class Example: NSObject {
         }
         group!.phase = .beforesFinished
 
-        closure()
+        do {
+            try closure()
+        } catch {
+            print("Test \(name) threw unexpected error: \(error.localizedDescription)")
```
Comment (marcelofabri) [inline Sources/Quick/Example.swift]: How to property report an error? I've tried `XCTFail`, but can't use the `callsite` information because of types (`StaticString` x `String`).

I wasn't able to get a reference to the `XCTestCase` that contains this example, but I think that would solve the issue as I could call [`recordFailure(withDescription:inFile:atLine:expected:)`](https://developer.apple.com/reference/xctest/xctestcase/1496269-recordfailure)

File: Tests/QuickTests/QuickTests/FunctionalTests/ItTests.swift [hunk 2]
```diff
@@ -101,6 +101,26 @@ class FunctionalTests_ItSpec: QuickSpec {
...
+
+                func throwingFunc() throws {
+                    throw ExampleError.error
+                }
+
+                it("supports calling functions marked as throws") {
+                    try nonThrowingFunc()
+                }
+
+                it("supports calling functions that actually throws") {
```
Comment (marcelofabri) [inline Tests/QuickTests/QuickTests/FunctionalTests/ItTests.swift]: I need a way to test this test as it'll fail once the implementation is correct. I've tried using the exception handling approach, but it doesn't seem like test failures create expections. I think I'd need something like `Nimble` uses to record assertions.

File: Sources/Quick/Example.swift (hunk 1 above)
Comment (jeffh) [inline Sources/Quick/Example.swift]: Hey @marcelofabri, I think the `Callsite` class will probably need to be refactored to use `StaticString` to use `XCTFail` as probably the best way to go

File: Tests/QuickTests/QuickTests/FunctionalTests/ItTests.swift (hunk 2 above)
Comment (jeffh) [inline Tests/QuickTests/QuickTests/FunctionalTests/ItTests.swift]: Would something like how [focused tests](https://github.com/Quick/Quick/blob/master/Tests/QuickTests/QuickFocusedTests/FocusedTests.swift) are executed work? I'm not as up to speed on the Quick side of the code for bootstrapping unfortunately, perhaps other @Quick/core can answer this better.

File: Sources/Quick/Example.swift (hunk 1 above)
Comment (marcelofabri) [inline Sources/Quick/Example.swift]: I've tried that, but it seems impossible because of Objective-C compatibility

Comment (marcelofabri) [inline Sources/Quick/Example.swift]: Once/if #645 is merged this will be trivial, as we could just use `QuickSpec.current.recordFailure`.

**Comment by gperdomor** [comment]
Any progress here?

**Comment by marcelofabri** [comment]
i was awaiting for #645 to be merged first, so we can use `QuickSpec.current.recordFailure(...)`

File: Tests/QuickTests/QuickTests/FunctionalTests/ItTests.swift [hunk 3]
```diff
@@ -106,10 +106,35 @@ class FunctionalTests_ItSpec: QuickSpec {
...
+            func throwingFunc() throws {
+                throw ExampleError.error
+            }
+
+            it("supports calling functions marked as throws") {
+                try nonThrowingFunc()
+            }
+
+            it("supports calling functions that actually throws") {
+                try throwingFunc()
```
Comment (marcelofabri) [inline Tests/QuickTests/QuickTests/FunctionalTests/ItTests.swift]: I couldn't find a way to do it without actually failing the suite. Any ideas?

**Comment by jwelton** [comment]
Any updates on this?

**Comment by ikesyo** [comment]
I'll take a look.

**Comment by davuthsina** [comment]
Any updates on this?

**Comment by forceunwrap** [comment]
Hey @ikesyo, as you self-assigned this issue, any update on this?

**Comment by ikesyo** [comment]
This should be now ready thanks to the series of pull requests: #645, #848, #850, #854, #879, #882, #883, #884, #885.

I think this is a breaking API change so it will need a major version bump (Quick v3).

**Comment by marcelofabri** [comment]
Thanks for picking this up! Excited that this is ready! ✨

**Comment by ZevEisenberg** [comment]
❤️ I'd love to test this out when it's ready. I was literally just looking for something like this to exist

**Comment by soaurabhtokopedia** [comment]
Hello @ikesyo @jeffh, Would love to see it getting merged. Looking for this functionality lately ❤️

**Comment by ikesyo** [comment]
[v2.2.1](https://github.com/Quick/Quick/releases/tag/v2.2.1) has been released so now it's time for heading to Quick v3. Merging.

**Comment by marcelofabri** [comment]
@ikesyo is there a list of things we want to land in v3? i'd love to see this released as soon as possible ❤️

**Comment by ikesyo** [comment]
@marcelofabri Sorry for the delay, just published! 🚢 

https://github.com/Quick/Quick/releases/tag/v3.0.0

**Comment by marcelofabri** [comment]
> @marcelofabri Sorry for the delay, just published! 🚢 
> 
> 
> 
> https://github.com/Quick/Quick/releases/tag/v3.0.0

Thanks so much! 😍🎉🍾🎊
