### PR TITLE
[1.x] Fix unrecognized selector crash on static linking

### LINKED ISSUE #785: Unrecognized Selector crash in QuickSpec.m on Xcode 9.3
When I try to run tests there is a crash in QuickSpec.m line 113:

_NSString *originalName = example.name.qck_c99ExtendedIdentifier;_

And it says:

2018-04-21 14:13:36.409506+0200 OneApp[90978:6333181] -[Swift._NSContiguousString qck_c99ExtendedIdentifier]: unrecognized selector sent to instance 0x604000455990

I got this crash since I use Xcode 9.3 and Swift 4.1. 
Quick version is 1.3.0

### PR DESCRIPTION
**Pull request by ikesyo**
~~Extension methods or properties for NSObject subclasses are somehow invisible from the Objective-C runtime on static linking, so let's make a wrapper class.~~

Extension methods or properties for NSObject subclasses are invisible from the Objective-C runtime on static linking unless the consumers add `-ObjC` linker flag, so let's make a wrapper class to mitigate that situation.

Fixes #785.

### CODE REVIEW

**Comment by ikesyo** [comment]
@zcsipler Could you try this branch?

**Comment by ikesyo** [comment]
Oh I completely forgot the linker flag! 💦 Indeed, adding the flag to test targets which uses Quick (e.g. `Quick - macOSTests`, `QuickFocused - macOSTests`, and so on), not to Quick itself, fixes the issue.

But forcing consumers to add the flag to their test targets just for this internal implementation detail will not be ideal I think. What do you think?

File: Sources/Quick/NSString+C99ExtendedIdentifier.swift [hunk 1]
```diff
@@ -22,12 +21,25 @@ public extension NSString {
         return invalidCharacters
     }()
 
-    @objc(qck_c99ExtendedIdentifier)
```
Comment (sharplet) [inline Sources/Quick/NSString+C99ExtendedIdentifier.swift]: Because there's a workaround, I think we should preserve this public API.

File: Sources/Quick/NSString+C99ExtendedIdentifier.swift [hunk 2]
```diff
@@ -22,12 +21,25 @@ public extension NSString {
...
 
         return result.isEmpty ? "_" : result
     }
 }
+
+/// Extension methods or properties for NSObject subclasses are somehow invisible
+/// from the Objective-C runtime on static linking, so let's make a wrapper class.
+///
+/// See: https://github.com/Quick/Quick/issues/785
+@objc
```
Comment (sharplet) [inline Sources/Quick/NSString+C99ExtendedIdentifier.swift]: Might be a good idea to prefix this new class?

File: Sources/Quick/NSString+C99ExtendedIdentifier.swift [hunk 3]
```diff
@@ -22,12 +21,25 @@ public extension NSString {
...
     var c99ExtendedIdentifier: String {
         let validComponents = components(separatedBy: NSString.invalidCharacters)
         let result = validComponents.joined(separator: "_")
 
         return result.isEmpty ? "_" : result
     }
 }
+
+/// Extension methods or properties for NSObject subclasses are somehow invisible
+/// from the Objective-C runtime on static linking, so let's make a wrapper class.
```
Comment (sharplet) [inline Sources/Quick/NSString+C99ExtendedIdentifier.swift]: Because we know that `-ObjC` will expose these to the runtime, this comment might need an update.

File: Sources/Quick/NSString+C99ExtendedIdentifier.swift (hunk 1 above)
Comment (ikesyo) [reply Sources/Quick/NSString+C99ExtendedIdentifier.swift]: I'm okay to preserve this for 1.x but I'd like to hide this in 2.x, because I assume the reason why this API is public is to expose it to the generated header. We can now expose internal Swift APIs to the generated header thanks to #791, so there will be no need to make it public.

Comment (sharplet) [reply Sources/Quick/NSString+C99ExtendedIdentifier.swift]: Can we explicitly deprecate it?

Comment (ikesyo) [reply Sources/Quick/NSString+C99ExtendedIdentifier.swift]: I tried adding `@available(*, deprecated)` but `__attribute__ ((deprecated))` is not exposed to the generated header unfortunately.

**Comment by ikesyo** [comment]
@sharplet Thanks for the detailed review! 💖 I updated the pull request.

**Comment by ikesyo** [comment]
Thanks!

> Is there somewhere in the documentation that we could add a tip about the -ObjC linker flag?

I will try to update `InstallingQuick.md` in a separate pr. Let's metge this as is.
